// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApI_X28Pk_LzQ4IPoZtJpwQ2oAYXP7R_Q',
    appId: '1:54244602831:web:8c2a04b750d0a7304b18ba',
    messagingSenderId: '54244602831',
    projectId: 'patient-vitals-app',
    authDomain: 'patient-vitals-app.firebaseapp.com',
    storageBucket: 'patient-vitals-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKv0IqiXRlHgndNh9NcAMzJBSzXYHjmbg',
    appId: '1:54244602831:android:60a49084df7990654b18ba',
    messagingSenderId: '54244602831',
    projectId: 'patient-vitals-app',
    storageBucket: 'patient-vitals-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_wJw9oLkGEiEEzrrm8E3xlYgqNVwN5E',
    appId: '1:54244602831:ios:db6c95e1a96937ae4b18ba',
    messagingSenderId: '54244602831',
    projectId: 'patient-vitals-app',
    storageBucket: 'patient-vitals-app.firebasestorage.app',
    iosBundleId: 'com.example.patientVitalsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_wJw9oLkGEiEEzrrm8E3xlYgqNVwN5E',
    appId: '1:54244602831:ios:db6c95e1a96937ae4b18ba',
    messagingSenderId: '54244602831',
    projectId: 'patient-vitals-app',
    storageBucket: 'patient-vitals-app.firebasestorage.app',
    iosBundleId: 'com.example.patientVitalsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApI_X28Pk_LzQ4IPoZtJpwQ2oAYXP7R_Q',
    appId: '1:54244602831:web:3c3db7f2d12071404b18ba',
    messagingSenderId: '54244602831',
    projectId: 'patient-vitals-app',
    authDomain: 'patient-vitals-app.firebaseapp.com',
    storageBucket: 'patient-vitals-app.firebasestorage.app',
  );
}
